spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.217.154:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: sa
    password: '#QAZqaz12'
    hikari:
      pool-name: hikariCP
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 60000
#  cache:
#    jcache:
#      config: classpath:ehcache.xml