server:
  port: 8080
spring:
  application:
    name: sb-jsmvc-spa
  profiles:
    active: prd
  jackson:
    serialization:
      fail-on-empty-beans: false

#logging:
#  level:
#    root: INFO
#    org.springframework: INFO
#    com.spa.demo: DEBUG