server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    hikari:
      pool-name: simpleCP
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 60000
  cache:
    jcache:
      config: classpath:ehcache.xml
logging:
  level:
    org.springframework: ERROR
    com.spa.demo: DEBUG